favorites/urls.py
from django.urls import path
from . import views

app_name = 'favorites'


urlpatterns = [
    path('fav_list/', views.fav_list, name='fav_list'),
    path('api/change/<int:ad_id>', views.fav_change, name='change'),
    path('remove/<int:ad_id>/', views.remove_fav, name='remove_fav'),
]

maimarket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from maimarket import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('goods/', include('goods.urls', namespace="goods")),
    path('favorites/', include('favorites.urls', namespace="favorites"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.main_page, name='home'),
    path('support/', views.support, name='support')
]

favorites/models.py
from django.contrib.auth import get_user_model
from django.db import models

from goods.models import Goods

class Favorites(models.Model):

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь')
    product = models.ForeignKey(to=Goods, on_delete=models.CASCADE, verbose_name='Товар')
    time_create = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранное'
        ordering = ['-time_create']

    def __str__(self):
        return f'Избранное пользователь {self.user} | товар {self.product.name}'


favorites/views.py

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect

from favorites.models import Favorites
from goods.models import Goods

# Список изранных товаров
@login_required
def fav_list(request):
    ads = Favorites.objects.filter(user=request.user)
    data = {'ads': ads}
    return render(request, 'favorites/fav_list.html', data)

# Добавление и удаление из избранного
@login_required
def fav_change(request, ad_id):
    product = Goods.objects.get(id=ad_id)
    favs = Favorites.objects.filter(user=request.user, product=product)
    if favs.exists():
        favs.delete()
        return JsonResponse({'is_favorite': False})
    else:
        Favorites.objects.create(user=request.user, product=product)
        return JsonResponse({'is_favorite': True})


def remove_fav(request, ad_id):
    fav = Favorites.objects.get(id=ad_id)
    fav.delete()

    return redirect(request.META['HTTP_REFERER'])


favorites/templates/favorites/fav_list.html
{% extends 'base_for_profile.html' %}
{% load static %}


{% block content_user %}

<h2 class="my-products__title h3">Избранное</h2>
<ul class="my-products__list">
{% for ad in ads %}
    <li class="my-products__item">
        <div class="my-products__item-wrapper">
            <div class="my-products__photo">
                <a href="{{ ad.product.get_absolute_url }}">
                <img class="my-products__image" src="{{ ad.product.image.url }}" alt="">
                </a>
            </div>
            <div class="my-products__info   ">
                <h3 class="my-products__name h4">{{ ad.product.name }}</h3>
                <p class="my-products__price">{{ ad.product.price }} <span>₽</span></p>

            </div>
        </div>
        <div class="my-products__btns">
            <a class="my-products__button button button--delete-from-likes" href="{% url 'favorites:remove_fav' ad.id %}">Убрать из избранного</a>
            <button class="my-products__button button button--delete-from-likes" >Написать</button>
            <button class="my-products__button button button--delete-from-likes" >Позвонить</button>
        </div>
    </li>
    {% endfor %}


</ul>

{% endblock %}