favorites/urls.py
from django.urls import path
from . import views

app_name = 'favorites'


urlpatterns = [
    path('fav_list/', views.fav_list, name='fav_list'),
    path('api/change/<int:ad_id>', views.fav_change, name='change'),
    path('remove/<int:ad_id>/', views.remove_fav, name='remove_fav'),
]

goods/urls.py
from django.urls import path
from . import views

app_name = 'goods'


urlpatterns = [
    path('additem/', views.AddAd.as_view(), name='add_ad'),
    path('ad/<slug:ad_slug>/', views.show_ad, name='ad'),
    path('list/', views.goods_list, name='goods_list'),
    path('edit/<slug:ad_slug>/', views.edit_ad, name='edit'),
    path('publish/<slug:ad_slug>/', views.remove_ad, name='publish'),
]

maimarket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from maimarket import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('goods/', include('goods.urls', namespace="goods")),
    path('favorites/', include('favorites.urls', namespace="favorites"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.main_page, name='home'),
    path('support/', views.support, name='support')
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordChangeDoneView

from . import views
from django.urls import path, reverse_lazy

app_name = 'users'

urlpatterns = [
    path('profile/<int:user_id>/', views.profile_goods, name='profile'),
    path('profile/not_published/', views.profile_unpublished_goods, name='profile_not_published'),
    path('profile/change_data/', views.edit_profile, name='profile_change_data'),
    path('profile/change_password/', views.UserPasswordChange.as_view(), name='password_change'),
    path('profile/change_password/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('verify_email/', views.verify_email, name='verify_email'),
    path('register_done/', views.register_done, name='register_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),

    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password_reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),

    path('password_reset_complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
         name='password_reset_complete')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'main/css/main.css'%}" rel="stylesheet">
    <script src="{% static 'main/js/main.js' %}" type="module" defer></script>
    {% block js %} {% endblock %}
</head>
<body>
    <header class="header" data-js-header>
      <div class="header__inner container">
        <a class="header__logo" href="/">
            <img class="header__logo-image" src="{% static 'main/img/mai_logo_color.png' %}" alt="MAI logo" width="100" height="100">
        </a>
        <form action="{% url 'goods:goods_list' %}" method="get" class="header__form">
            {% csrf_token %}
            <input type="text" name="query" placeholder="Поиск товаров..." class="header__form-search">
            <button class="header__form-search-button" type="submit">Найти</button>
        </form>

        <nav class="header__menu " data-js-header-overlay>
            <ul class="header__menu-list">
                <li class="header__menu-item">
                    <a class="header__menu-link header__menu-link--heart" href="{% url 'favorites:fav_list' %}">Избранное</a>
                </li>
                <li class="header__menu-item">
                    <a class="header__menu-link header__menu-link--folder" href="{% url 'goods:goods_list' %}">Лента товаров</a>
                </li>
                <li class="header__menu-item ">
                    <a class="header__menu-link header__menu-item--info " href="{% url 'goods:add_ad' %}">Разместить объявление</a>
                </li>

                <li class="header__menu-item ">
                    <a class="header__menu-link header__menu-item--mail" href="{% url 'support' %}">Поддержка</a>
                </li>

              <li class="header__menu-item">
                  {% if user.is_authenticated %}
                  <a class="header__menu-link" href="{{ request.user.get_absolute_url }}">
                    <span class="profile">
                    <span class="profile__logo">
                        {% if user.photo %}
                        <img class="profile__logo-image" src="{{ request.user.photo.url }}" alt="" width="35" height="35">
                        {% else %}
                        <img class="profile__logo-image" src="{% static 'main/img/anonim.png' %}" alt="" width="35" height="35">
                        {% endif %}
                    </span>
                      <span class="profile__name">{{ request.user.username }}</span>
                    </span>
                  </a>
                {% else %}
                <a class="header__menu-link" href="{% url 'users:login' %}">
                    <span class="profile">
                      <span class="profile__name">Вход</span>
                    </span>
                </a>
                {% endif %}
                </li>
            </ul>
        </nav>

        <button type="button" class="header__burger-button  burger-button visible-tablet " data-js-header-burger-button  aria-label="Open menu" title="Open menu">
          <span class="burger-button__line"></span>
          <span class="burger-button__line"></span>
          <span class="burger-button__line"></span>
        </button>
      </div>
    </header>

{% block content %} {% endblock %}

</body>
</html>

templates/base_for_forms.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAI Registration</title>
    <link rel="stylesheet" href="{% static 'main/css/main.css'%}">
    <script src="{% static 'main/js/form-log.js'%}" defer></script>

</head>
<body>
    <section class="registration-login">
        {% block content %} {% endblock %}
    </section>
</body>
</html>

templates/base_for_profile.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<main class="main">
    <section class="section container">
        <header class="section__header ">
            <h1 class="section__header-title h2">Профиль</h1>
        </header>
        <div class="section__body">
            <div class="profile-page" data-js-tabs>
                <aside class="profile-page__aside">
                    <div class="profile-page__header">
                        {% if user.photo %}
                        <img class="profile-page__image" src="{{ user.photo.url }}" alt="" width="100" height="100">
                        {% else %}
                        <img class="profile-page__image" src="{% static 'main/img/anonim.png' %}" alt="" width="100" height="100">
                        {% endif %}
                        <div class="profile-page__character">
                            <p class="profile-page__last-name h4">{{ user.last_name }}</p>
                            <p class="profile-page__name h4">{{ user.first_name }}</p>
                        </div>
                    </div>
                    <div class="profile-page__body ">
                        <div class="tabs">
                            {% if user == request.user %}
                            <a href="{{ request.user.get_absolute_url }}" class="tabs__button button button--blue">
                                Мои товары
                            </a>
                            <a href="{% url 'users:profile_not_published' %}" class="tabs__button button button--blue">
                                Мои неопубликованные товары
                            </a>
                            <a href="{% url 'favorites:fav_list' %}" class="tabs__button button button--blue">
                                Избранное
                            </a>
                            <a href="{% url 'users:profile_change_data' %}" class="tabs__button button button--blue">
                                Редактировать профиль
                            </a>

                            <a href="{% url 'goods:add_ad' %}" class="tabs__button button button--blue">
                                Добавить товар
                            </a>
                            <form method="post" action="{% url 'users:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="tabs__button button button--blue">
                                Выйти из профиля
                            </button>
                            </form>
                            {% else %}
                            <div class="profile-page__body profile-page__body--users">
                                <a href="https://t.me/{{ user.telegram }}" class="button button--blue">Написать</a>
                                <button class="button button--green">Позвонить</button>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </aside>

                    <div class="profile-page__main">
                    <div class="profile-page__main-wrapper">
                {% block content_user %} {% endblock %}
                    </div>
                    </div>
                </div>
            </div>
      </section>
</main>
{% endblock %}